ALTER TABLE IF EXISTS users
    ADD PRIMARY KEY (id),
    ALTER COLUMN user_id SET NOT NULL,
    ALTER COLUMN username SET NOT NULL,
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN reg_date SET NOT NULL;


ALTER TABLE IF EXISTS admins
    ADD PRIMARY KEY (id),
    ALTER COLUMN username SET NOT NULL;


ALTER TABLE IF EXISTS orders
    ADD PRIMARY KEY (id),
    ALTER COLUMN order_id SET NOT NULL,
    ALTER COLUMN user_id SET NOT NULL,
    ALTER COLUMN service_id SET NOT NULL,
    ALTER COLUMN order_date SET NOT NULL;


ALTER TABLE IF EXISTS contacts
    ADD PRIMARY KEY (id),
    ALTER COLUMN user_id SET NOT NULL,
    ALTER COLUMN first_name SET NOT NULL,
    ALTER COLUMN last_name SET NOT NULL,
    ALTER COLUMN phone SET NOT NULL;
